First two modules in a form of a huuuuuuge blob.
G1gg1L3s/crypto pull request #1
Opened 2021-03-02 18:39 UTC by G1gg1L3s

2021-03-02 19:14 UTC, storojs72 commented
As a first common remarks, please make following improvements:
1) add detailed description of your work (it should contain information about proposed solution, testing details, some important notes for reviewers that would save time on digging in your code);
2) as a continuation of first point - add instructions how to run your code; 
3) add signing git commits (https://docs.github.com/en/github/authenticating-to-github/signing-commits).

2021-03-03 18:46 UTC, storojs72 commented
Took a short second look. @G1gg1L3s at frist, please, reorganize codebase to be a workspace with internal rust crates (`poly`, `hack_aes`, `pals1`, `pals2`, etc). And secondly, when PR is created, please write a detailed description, don't leave it empty (for current PR you can at least copy-paste the info - how to run your binaries from README). This is ultimately important especially for such big PRs with 99 files changed!

2021-03-10 19:54 UTC, storojs72 requested changes
PALS1
Challenge 1 - OK
Challenge 2 - OK
Challenge 3 - OK (Do you like Sherlock Holmes stories?)

Will review other challenges later. The only general comment - add please more user friendly error handling for all your command line applications instead of just crashing for corner cases:
```
artem@artem:~/CossackLabs/internship/nazar/crypto$ cargo run --bin sb-xor ffffff3331363f78151b7f2b783400333d78397828372d363c78373e783a393bfff
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/sb-xor ffffff3331363f78151b7f2b783400333d78397828372d363c78373e783a393bfff`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Odd length"', pals1/src/bin/sb-xor.rs:8:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

You can use printing error message and exiting with non-zero code for example.

Question: just out of curiosity what IDE do you use for development (it is not an IntellijIDEA as far as I don't see `.idea` in `gitignore`)?

2021-03-10 19:54 UTC, storojs72 commented on hack_aes/.gitignore
> +Cargo.lock
Should we keep `Cargo.lock` file in gitignore for Rust command-line tools?

2021-03-10 19:54 UTC, storojs72 commented on pals1/src/bin/xor.rs
> +    assert!(
Should we may be use more idiomatic `assert_eq`?

2021-03-10 20:36 UTC, G1gg1L3s commented on .gitignore
> +/.vscode
Yep, something went wrong with my formatter

2021-03-10 20:37 UTC, G1gg1L3s commented on hack_aes/.gitignore
> +Cargo.lock
I actually didn't know that, I thought Cargo.lock is an artifact that you shouldn't include. And it turns out that it's true only for lib crates. Thanks.

2021-03-10 21:09 UTC, G1gg1L3s commented on pals1/src/bin/xor.rs
> +    assert!(
Yes, that makes sense.

2021-03-10 21:17 UTC, G1gg1L3s commented
I actually have never read Sherlock Holmes stories, it's just the first book that came to my mind :)
Personally, I'm not a big fan of IDE, I prefer vscodium with a bunch of plugins, that's why you can sometimes find `.vscode` folders.

Also, this process of pull requesting and reviewing is kinda new for me. I have seen how it is done before, but never actually done it by myself, so if I do something wrong, please let me know :)
And one more thing, should I go and just check every file for similar errors and fix them? Is it done this way?

2021-03-11 15:45 UTC, storojs72 commented
> And one more thing, should I go and just check every file for similar errors and fix them? Is it done this way?

If you mean iterating each `main` function and replace crashing on user-friendly exiting - I would suggest to do so. I understand that main purpose of this exercises is learning - but nevertheless, let's follow best software engineering practices.

2021-03-11 16:44 UTC, storojs72 requested changes
PALS1
Challenge 1 - OK
Challenge 2 - OK
Challenge 3 - OK
Challenge 4 - OK
Challenge 5 - OK
Challenge 6 - OK
Challenge 7 - OK
Challenge 8 - OK

Remarks:
1) That's a logical continuation of previous suggestion for user-friendly exiting in case of some unexpected input. Command line tools (it is not only for Rust but for any programming language) should provide descriptive explanation of available flags. Common practice is including `--help` flag that prints some default message. For example consider `git --help`:
```
artem@artem:~/CossackLabs/internship/nazar/crypto$ git --help
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

 . . .
```
That is much more better than:
```
artem@artem:~/CossackLabs/internship/nazar/crypto$ cargo run --bin detect-sb-xor -- --help
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/detect-sb-xor --help`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', pals1/src/bin/detect-sb-xor.rs:11:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I do not insist on manually writing parser for command line arguments, but strongly recommend to use some already available projects for Rust language (they are also available for any other language) that specifically designed to provide mentioned arguments handling.

2) If we use different file for checking it also crashes:
```
artem@artem:~/CossackLabs/internship/nazar/crypto$ cargo run --bin detect-sb-xor pals1/7.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/detect-sb-xor pals1/7.txt`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Invalid hex character"', pals1/src/bin/detect-sb-xor.rs:13:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
A good indicator for proper input validation is a "Monkey test" - when you put different random strings with special characters. Also usually some corners are tested, like empty input

2021-03-11 16:44 UTC, storojs72 commented on pals1/src/bin/rk-xor.rs
> +    let buffer: Vec<_> = {
Should we may be foresee unlocking by timer? Currently program terminates infinitely if nothing is presented in `stdin`

2021-03-11 17:48 UTC, G1gg1L3s commented on pals1/src/bin/rk-xor.rs
> +    let buffer: Vec<_> = {
Is it done this way? I mean, I have never seen programs that have such timer, except of course password entry.

2021-03-12 17:16 UTC, storojs72 commented on pals1/src/bin/rk-xor.rs
> +    let buffer: Vec<_> = {
Take a look at [asynk-std](https://docs.rs/crate/async-std/1.5.0) Rust crate. May be it will give you some ideas!

2021-03-22 18:16 UTC, storojs72 reviewed
CryptoHack - general

Encodings - OK
Encodings Challenge - OK
XOR - OK
Mathematics - OK
Data Formats - OK

1) Minor. Thank you for using `clap` and making your applications more standardized. I would only point that for example for `general/encoding` program, you could provide 4 flags:
- ascii
- hex
- base 64
- bytes_and_bigints

and make your app configurable. For instance if we run it with `cargo run --bin encoding -- --hex` it should return just one string: `Hex = You_will_be_working_with_hex_strings_a_lot`. Because now your programs just provide `--help` and `--version` flags - which is out of the box in `clap` without actual configuration power.

2)  Interest thing about transparency. Would you like to dig more on how it works? We currently have a project which is closely related to transparency domain. There is an excellent [blog-post ](https://research.swtch.com/tlog) about internals of server that maintains public append-only log. May be you can read it and write a short report for the next call, if you have a time of course

2021-03-22 18:37 UTC, storojs72 reviewed
PALS2

Challenge 9 - OK
Challenge 10 - OK
Challenge 11 - OK
Challenge 12 - OK
Challenge 13 - OK
Challenge 14 - OK
Challenge 15 - OK
Challenge 16 - OK

2021-03-22 18:37 UTC, storojs72 commented on pals2/src/bin/detec-oracle.rs
> +fn detelection_oracle() {
Did you mean `detection_oracle`?

2021-03-22 18:37 UTC, storojs72 commented on pals2/src/bin/detec-oracle.rs
> +        (aes_cbc_enc(buff, &key, &iv), Mode::Cbc)
A bit confusing syntax. Plus, your function name `aes_cbc_enc` already has information of what it intends to do - encrypt, using CBC mode. I would avoid using redundant `Mode::Cbc`. May be it is better to have `aes_enc` function that would allow some parametrized input - e.g. `encParameters` expressed as a separate trait, where you can specify the mode of encryption and configure data (for CBC we need and IV)

2021-03-22 19:11 UTC, G1gg1L3s commented on pals2/src/bin/detec-oracle.rs
> +        (aes_cbc_enc(buff, &key, &iv), Mode::Cbc)
The only purpose of this enum is to return information about which encryption algorithm was used, so we can lately verify our guess.

2021-03-22 19:11 UTC, G1gg1L3s commented on pals2/src/bin/detec-oracle.rs
> +fn detelection_oracle() {
Yep

2021-03-22 19:14 UTC, G1gg1L3s commented
I'm definitely gonna take a look at that blog-post. That sounds super interesting

2021-03-23 15:44 UTC, storojs72 commented on pals2/src/bin/detec-oracle.rs
> +        (aes_cbc_enc(buff, &key, &iv), Mode::Cbc)
That is the case. Using `aes_cbc_enc` already gives all necessary information - that CBC mode of AES is going to be used. And additional `Mode::Cbc` parameter seems redundant, isn't it?

2021-03-23 15:46 UTC, storojs72 commented
PALS3

Challenge 17 - OK
Challenge 18 - OK
Challenge 19 - OK
Challenge 20 - OK
Challenge 21 - OK
Challenge 22 - OK
Challenge 23 - OK
Challenge 24 - OK

Now I'm sure you will definitely use cryptographic PRNG in any crypto-related task!

2021-03-23 15:58 UTC, G1gg1L3s commented on pals2/src/bin/detec-oracle.rs
> +        (aes_cbc_enc(buff, &key, &iv), Mode::Cbc)
But our encryption_oracle function encrypts randomly in CBC or ECB and we don't know which mode is used, so we can not be sure about our guess. So, I return this enum just to check it later.

2021-03-23 16:00 UTC, storojs72 commented
Could you please rephrase / provide more explanations to the tasks according to the modules? I don't clearly understand what parts of `hack_aes` relate to tasks in `CryptoHack Block Ciphers`.

2021-03-23 16:05 UTC, G1gg1L3s commented
Are you talking about the names of binaries?

2021-03-23 16:10 UTC, storojs72 commented
No, I mean names of tasks according to modules from your internship program

2021-03-23 16:18 UTC, G1gg1L3s commented
As I get, you don't understand which of the tasks from hack_aes are related to the `CryptoHack Block Ciphers`? But they all. On the main page of cryptohack this section is called `Block Ciphers` but link to that section is `https://cryptohack.org/challenges/aes/`, that's why I called this crate `hack_aes`. Did i understand the question correctly?

2021-03-23 16:29 UTC, storojs72 commented
From your internship program:
```
Module 1
- pals1 (70% of tasks)
- hack intro (100% of tasks)
- hack general part 1 - first 9 tasks from 18 (30% of tasks)

Module 2
- pals2 (70% of tasks);
- pals3 (70% of tasks)
- hack general part 2 - last 9 tasks from 18 (60% of tasks)
- hack block ciphers (60% of tasks)

Module 3
- pals4 (60% of tasks);
- pals5 (60% of tasks);
- hack general (80% of tasks - but you really should have almost of them from previous modules);
- hack dh (60% of tasks).

Module 4
- pals 6 (60% of tasks);
- hack rsa (60% of tasks);
- hack ecc (60% of tasks);
```

In your PR - I saw:
- pals1 (100%);
- pals2 (100%);
- pals3 (100%);
- hack general (100%);
- hack block ciphers (that you called hack_aes, right?) - and I can't identify how much is done, since naming is different

2021-03-23 16:38 UTC, G1gg1L3s commented
Yep, hack block ciphers is hack_aes. And as I understand, I didn't have to do all the tasks, just some of them? :)

2021-03-24 17:21 UTC, storojs72 requested changes
HACK GENERAL:

AES tasks - OK;
Block Cipher Modes tasks - OK;
ECB - OK;
CBC- OK;
OFB - OK;
CTR - OK;
GCM - OK;
Other modes - OK;
Other ciphers - OK;

Some remarks:

1) Did you use `nightly` version of rust toolchain for some programs? I encountered following error while running `matrix` task:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> hack_aes/src/lib.rs:1:1
  |
1 | #![feature(num_as_ne_bytes)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

```
But it compiles and normally runs if I use `nightly` instead of `stable` toolchain. If so, then please in future include such kind of information into README / description of PR since this is quite important. Usually it is better to use stable version of software instead of experimental - since last is often a subject of frequent breaking changes.

2) I would suggest to always use `unwrap` with caution. It's OK to us it in such place:
```
String::from_utf8(vec![0x20, 0x21, 0x22]).unwrap()
```
because you definitely know that no errors will occur. In other cases we should always consider better error handling strategies

2021-03-24 17:21 UTC, storojs72 commented on hack_aes/src/bin/bean-counter.rs
> +    file.write_all(&png).unwrap();
Sometimes you are unable to write into file, due to lack of permissions or read-only disk drives. Should we think about handling such errors more user-friendly than just `unwrap` and crashing the program?

2021-03-24 17:48 UTC, G1gg1L3s commented on hack_aes/src/bin/pass.rs
> +        if let Ok(plaintext) = String::from_utf8(plaintext) {
Generally yes, but in this case we shouldn't. We are iterating over the passwords and trying to decrypt our text with a key that is derived from a password. Also we know that we should get some string in a form of `crypto{...}`, so we know that it's valid utf8, and we know that if we don't hit the valid utf8, it's definitely not the right key and not the right password.
But there is another issue in this program: if we didn't find any password, our program will print nothing. So, I'm going to change this.

2021-03-24 17:51 UTC, G1gg1L3s commented on hack_aes/src/bin/rc4.rs
> +        if let Ok(res) = ureq::get(&url).call() {
Yes, it should be fixed. I've included this loop because when program makes a lot of requests some of them start to fail, which crashes the program and all progress of cracking the flag. And this loop helps preventing it. Maybe I should add some parameter for maximum number of tries?

2021-03-24 17:54 UTC, G1gg1L3s commented on hack_aes/src/bin/bean-counter.rs
> +    file.write_all(&png).unwrap();
Yep, It's just something I missed when refactoring errors.

2021-03-24 18:01 UTC, G1gg1L3s commented on hack_aes/src/bin/sub-bytes.rs
> +    println!("{}", String::from_utf8(bytes).unwrap());
Ok, I will refactor it

2021-03-24 18:52 UTC, G1gg1L3s commented on hack_aes/src/bin/rc4.rs
> +        if let Ok(res) = ureq::get(&url).call() {
As I understand, this is the same comment as a previous one? Should I remove this?

2021-03-29 16:14 UTC, storojs72 commented on hack_aes/src/bin/rc4.rs
> +        if let Ok(res) = ureq::get(&url).call() {
Yes. this is an expected solution

2021-03-29 16:15 UTC, storojs72 commented on hack_aes/src/bin/rc4.rs
> +        if let Ok(res) = ureq::get(&url).call() {
Yes. If you can avoid this somehow - it is great. Or you should introduce number of tries and get url in a loop not more than number of tries

2021-03-29 16:18 UTC, storojs72 approved these changes
Only very minor things are left - not related to correctness of tasks solving. So I think it should be approved

2021-03-29 18:50 UTC, merged